transferred navbar changes from impact-page-tanaya
uclaacm/website pull request #283
Opened 2021-09-25 03:31 UTC by tnawathe21

Very rough change -- added initiatives section to the mobile and desktop view of the website

2021-09-25 04:39 UTC, mattxwang requested changes
Thanks Tanaya! A couple of quick things:

* do you mind resolving the merge conflict? happy to lend a hand if it's a struggle
* can you take a look at the next build error?

Also left some tiny code comments below!

2021-09-25 04:39 UTC, mattxwang commented on components/Navbar.js
> +					<li><Link href={''}><a>Jedi</a></Link></li>
```suggestion
					<li><Link href={'/jedi'}><a>JEDI</a></Link></li>
```

2021-09-25 04:39 UTC, mattxwang commented on components/Navbar.js
> +							<li className="initiatives"><Link href="/impact"><a>Initiatives</a></Link></li>
```suggestion
```

For now, let's remove this - we'll later make an initiatives page.

2021-10-11 00:42 UTC, mattxwang commented
@advaithg tagging you in on this

2021-11-16 05:23 UTC, mattxwang commented
@advaithg do you plan on taking this up? If not, going to toss it to @reginawang3495 and TLA

2021-11-16 05:26 UTC, advaithg commented
> going to toss it to @reginawang3495 and TLA

sounds good! I'm fine w that!

2021-11-16 05:33 UTC, mattxwang commented
See #351.

2021-12-03 22:58 UTC, closed without merging