Unify officer cards.
uclaacm/website pull request #333
Opened 2021-10-31 08:55 UTC by dtjanaka

Addresses https://github.com/uclaacm/website/issues/264

2021-10-31 17:37 UTC, advaithg requested changes
Since the card files were removed, did you also remove the now irrelevant SCSS styling from `jedi.module.scss` and `impact.module.scss`?

2021-10-31 17:37 UTC, advaithg commented on pages/impact.js
> +          </a>{' '}
Maybe this should be using `&nbsp;` instead of `{' '}`?

2021-10-31 17:37 UTC, advaithg commented on pages/jedi/meet.js
> +          not pictured:{' '}
Same comment on `&nbsp;`

2021-10-31 17:37 UTC, advaithg commented on pages/jedi/meet.js
> +            Email:{' '}
Same comment on `&nbsp;`

2021-10-31 19:28 UTC, mattxwang requested changes
Exciting stuff! I'll just comment with some overall things to consider:

1. When possible, I would take advantage of the `children` prop; you can write a unified wrapper for mobile / column-wrapping behaviour (a "base" officer card of sorts), and then fill in the relevant information that differs based on the context as a child (ex "Class of...", position information, committee etc. This [composition vs inheritance](https://reactjs.org/docs/composition-vs-inheritance.html#specialization) section in the React docs explains the "React way" of doing this!
2. If you want to simplify the props chain, you can create a schema for an "Officer" object that has some mandatory fields (name, pronouns, position, ...) and then pass that in. Optional props like committee or bio can then be passed in, but you can simplify usage a little bit! 
3. The styling for the compact leadership card is not very good; feel free to rework this however you want!
4. For the tab whitespace changes, you may get a cleaner diff if you open a different PR with just the whitespace changes, rebase this PR off that branch, and then merge that first. Thanks for catching the tab inconsistency!

2021-11-29 07:04 UTC, dtjanaka commented
> Since the card files were removed, did you also remove the now irrelevant SCSS styling from `jedi.module.scss` and `impact.module.scss`?

Done.

2021-11-29 09:41 UTC, mattxwang approved these changes
I'll leave it to Advaith to give a final review, but I personally think the changes look + work well! Solid work as always, Dylon! 

(feel free to punt the feedback from my previous review somewhere else - I know it's quite a bit)

2021-11-30 05:44 UTC, advaithg requested changes
Just noticed an error with the bigger officer cards when viewing it on smaller viewports!
The image sizes for the cards on the dev team page / the impact page remain the same even when resizing to tablet view.

![impact page tablet view in deploy preview](https://user-images.githubusercontent.com/67539191/143992205-87b99092-24bb-4c48-85d1-60c1a9338dba.png)
![dev team page tablet view in deploy preview](https://user-images.githubusercontent.com/67539191/143992274-dd501462-4042-46ad-96b8-e33b60c1f02c.png)

as opposed to what they should look like:

![impact page tablet view on website](https://user-images.githubusercontent.com/67539191/143992329-bb59d0b8-c5ce-43bb-8b91-ecbce8c50dc7.png)
![dev team page tablet view on website](https://user-images.githubusercontent.com/67539191/143992305-1e4f230e-5177-46a2-bfa4-4dd0c71d956d.png)

2021-11-30 05:45 UTC, advaithg reviewed
Other than that, it looks good - so we should be good to merge once that's fixed! I'll take into account Matt's previous review as long-term things we should do or issues we can give interns / tla dev team!

2022-03-26 21:47 UTC, advaithg reviewed
Feel free to re-request review once you're done with the changes!

2022-04-01 21:34 UTC, advaithg approved these changes
looks good! thanks for working on this Dylon!

2022-04-01 21:35 UTC, advaithg commented
@matthewcn56  make sure you take a look at this pr and merge main into your branch before updating leadership!

2022-04-01 21:37 UTC, merged

2022-04-02 00:12 UTC, matthewcn56 commented
alright will take a looksie!