Issue 371: Moved Teach LA images to our own site and used the Image tag
uclaacm/website pull request #394
Opened 2022-01-13 04:10 UTC by ichettiath

The profile pics of the Teach LA officers were taken from Teach LA's website. The images were moved to our own site and `<img >` tags were replaced with `<Image />` tags.

2022-01-14 06:38 UTC, advaithg requested changes
This looks good! Thanks for doing this + also switching to `Next/Image`
The only change I have is to reorder the `Image from next\image` import to be above the react import, like the warning says.

2022-01-14 06:39 UTC, advaithg reviewed
something like "closes #371" or "resolves #371" in the issue description will automatically close the issue as well

2022-01-24 16:31 UTC, merged

2022-01-24 18:57 UTC, mattxwang reviewed
I think there's some cleanup for this PR that needs to be done, @advaithg @ichettiath

2022-01-24 18:57 UTC, mattxwang commented on components/Impact/PersonCard.js
>  				{/* eslint-disable-next-line @next/next/no-img-element */}
Should remove this comment now

2022-01-24 18:57 UTC, mattxwang commented on components/JEDI/JEDICard.js
>        {/* eslint-disable-next-line @next/next/no-img-element */}
Should also remove this comment now