Update ACM COVID Policies page
uclaacm/website pull request #480
Opened 2022-04-11 17:14 UTC by alireza-jahandoost

Change everything specified in [issue #479](https://github.com/uclaacm/website/issues/479)

2022-04-11 21:06 UTC, matthewcn56 requested changes
Thanks for taking a stab at this! There's just a couple small things I left in like the proper link for the iframe and adding in a hyperlink to ucla's covid updates, but other than that it looks great!

2022-04-11 21:06 UTC, matthewcn56 commented on pages/covid.js
> +          src="https://docs.google.com/document/d/1IcBZ4yj4kJ14Gg0PVw3xbg-QqRYUQGUlHm8vVskgQOQ/edit?usp=sharing"
For the embedded iframe, you have to use a special link made by publishing a google docs page to the web, here's the correct link! https://docs.google.com/document/d/e/2PACX-1vQIXLd4Omqv2XaDflpIlbmyfYyXC0GhE64XbS1kakNOHf-9PauJnIBTiNFz_rEQteixMecfN8fKld5v/pub?embedded=true

2022-04-11 21:06 UTC, matthewcn56 commented on pages/covid.js
> +                  : Updated based on UCLA&apos;s Updates on COVID-19 Protocols for Spring Quarter
Can you please embed a link into the `UCLA's Updates on COVID-19 Protocols for Spring Quarter` to point to UCLA's covid guidelines like done in the other bullet points? https://covid-19.ucla.edu/update-on-covid-19-protocols-for-spring-quarter/

2022-04-12 05:52 UTC, alireza-jahandoost commented
@matthewcn56 I've done the change requests. please check again.

2022-04-12 06:16 UTC, matthewcn56 approved these changes
Looks great, thanks for doing this!

2022-04-12 06:16 UTC, merged